// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var Component1$ReactHooksTemplate = require("./Component1.bs.js");
var Component2$ReactHooksTemplate = require("./Component2.bs.js");

var options = {
  apiKey: "AIzaSyA9FXZSfWqnA2a3oQiKDdpVcyqtnm5fK10",
  authDomain: "litorsht.firebaseapp.com",
  databaseURL: "https://litorsht.firebaseio.com",
  projectId: "litorsht",
  storageBucket: "litorsht.appspot.com",
  messagingSenderId: "435093612673",
  appId: "1:435093612673:web:ae728305300a7ec8a04580",
  measurementId: "G-E06V413R2V"
};

window.firebase.initializeApp(options);

function getAllParks(param) {
  return window.firebase.firestore().collection("parks").get().then((function (value) {
                console.log(value);
                return Promise.resolve(value);
              }));
}

getAllParks(/* () */0);

ReactDOMRe.renderToElementWithId(React.createElement(Component1$ReactHooksTemplate.make, {
          message: "Hello! Click this text."
        }), "index1");

ReactDOMRe.renderToElementWithId(React.createElement(Component2$ReactHooksTemplate.make, {
          greeting: "Hello!"
        }), "index2");

exports.options = options;
exports.getAllParks = getAllParks;
/*  Not a pure module */
